<div>
<p><strong>MENAM Art Map</strong> is an interactive visualization of the institutional connections, life trajectories and centers of prominent members of the Middle Eastern art scene exhibiting in the west. The geo-spatial network representation is based on information extracted from a large corpus of artist biographies. </p>
<p>Each individual biography is a self-representation shaped by the artist’s personal emphasis, but also by the embedded values, expectations and institutional politics of the art world. A biography is a portrait that highlights certain aspects and omits others. By itself, a single biography is of limited value for understanding how artists of Middle Eastern origin enter in international art scene, or how the notion of Middle Eastern art is constructed through the international art institutions. But if several hundred biographies are aggregated and analyzed as a text corpus, common features and patterns start to emerge. By identifying dates, locations, personal trajectories, and institutions such as museums, galleries, festivals and academies, we hope not only to investigate the relationship on the MENAM art scene compared to the international art world, but also to reveal characteristics of the institutional context these artists are embedded in.</p>
<p>MENAM Art Map is an experiment in what literary scholar Franco Moretti calls “Distant Reading” using computational means such as natural language processing and advances in multi-dimensional networks. It represents the first stage of a research project dedicated to the analysis of text-networks at the Center for Texts, Maps and Networks at Northeastern University, Boston.</p>
<p>Team: Dietmar Offenhuber, Nick Beauchamp, Chris Riedl, Armin Akhavan<p/>
<p>Dietmar Offenhuber is Assistant Professor at Northeastern University in the departments of Public Policy and Urban Affairs and Art + Design, where he heads the MFA program in Information Design and Visualization. He holds a PhD in Urban Studies from MIT, and degrees from the MIT Media Lab and UT Vienna. His research focuses on the role of data representations in urban governance and civic discourse. Dietmar published books on the subjects of Urban Data, Accountability Technologies and Urban Informatics. In his artistic practice, Dietmar frequently collaborates with the sound artist Markus Decker and composers Sam Auinger and Hannes Strobl under the name “stadtmusik.” His artistic work has been exhibited internationally in venues including the Centre Georges Pompidou, MoMA New York, the Moscow Museum of Modern Art, the Anthology Film Archives NY, Sundance and the Hong Kong International Film Festivals, ZKM Karlsruhe, Secession Vienna, and the Seoul International Media Art Biennale.</p><p>web: http://offenhuber.net  email: d.offenhuber@neu.edu </p>
<p>Professor Nick Beauchamp research examines how political opinions form and change as a result of discussion, deliberation and argument in domains such as legislatures, campaigns, social media, and the judiciary, using techniques from machine learning, automated text analysis, and social network analysis.  His recent work examines deliberative quality in online political forums; predicts elections using Twitter textual data; tests the representativeness of UK legislators based on their text-derived ideology; and visualizes the rhetorical structures of political speeches.  Current projects include experimental methods for optimizing political advertisements, and the prediction of judicial opinions and ideologies.web: http://www.nickbeauchamp.com/ email: n.beauchamp@neu.edu </p>
<p>Christoph Riedl is assistant professor for Information Systems at Northeastern University. He holds appointments at the D’Amore-McKim School of Business and the College of Computer & Information Science. He is a core faculty at the NULab for Texts, Maps, and Networks. He is also a fellow at the Institute for Quantitative Social Science (IQSS) at Harvard University and a fellow of the NASA Tournament Lab. He is recipient of a Young Investigator Award (YIP) for his work on social networks in collaborative decision-making. Before joining Northeastern University he was a post-doctoral fellow at Harvard Business School and IQSS. He received a PhD in Information Systems from Technische Universität München (TUM), Germany in 2011, a MSc in Information Systems in 2007, and a BSc in Computer Science in 2006.<p>web: http://christophriedl.net/ email: c.riedl@neu.edu </p></p>

<p>Armin Akhavan has a BA in Urban Planning from Tehran University, Iran, an MS in Urban and Regional Policy from Northeastern University, and is currently studying for a MFA in Information Design at Northeastern. Since 2013, he has been working in projects ranging from scenario modeling, land-use planning, and data mining/predictive analysis to data visualization, web development and design. He is interested in working on web-based application projects aimed at perpetuating civic good. His other interests include interactive front-end design, web-mapping, and database development for web.</p><p>email: akhavan.a@husky.neu.edu</p>
</div>